from . import service
from . import lead
from . import service_relation
from . import sale_order_line
from . import res_partner
from . import ean
from . import contract
from . import sale_order
from . import opportunity_counter